server:
  port: 80

spring:
  application:
    name: "np"
  datasource:
    url: jdbc:mysql://192.168.100.128:3306/db_server1
    username: root
    password: mysqlpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 1           # redis数据库索引
    host: 127.0.0.1       # redis服务器地址
    port: 6379            # redis服务器连接端口
    jedis:
      pool:
        max-active: 20    # 连接池最大连接数
        max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中最大空闲连接
        min-idle: 0       # 连接池中最小空闲连接
    timeout: 1000         # 连接超时时间（毫秒）
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
app:
  swagger:
    enable: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml